package unbound

import (
	"fmt"
	"strings"
)

// ── 五源合成（§2.3：上游+转发+解析记录+封禁+参数 → 单一 unbound.conf）──
// 输入为纯数据类型（main 从各模块仓储映射），避免 engine→module 反向依赖。

// ConfInput 五源合成输入。
type ConfInput struct {
	SettingsBlock string            // 已渲染的 server: 参数段（dns.RenderSettingsBlock）
	DefaultFwd    []string          // 默认上游地址（含端口）
	Rules         []ForwardRuleConf // 条件转发规则（enabled）
	AuthZones     []AuthZoneConf    // 本地区域及其记录
	RpzZones      []RpzZoneConf     // 封禁 RPZ 区（zonefile 路径引用）
}

type ForwardRuleConf struct {
	Domain string
	Addrs  []string
}

type AuthZoneConf struct {
	Name    string
	Records []ZoneRecord
}

type ZoneRecord struct {
	Name string // FQDN 或相对名
	Type string
	TTL  int
	Data string
}

type RpzZoneConf struct {
	Name         string // 如 students.rpz
	ZonefilePath string
}

// BuildConf 合成完整 unbound.conf 文本。
func BuildConf(in ConfInput) string {
	var sb strings.Builder

	sb.WriteString("# Generated by ipam control-plane — DO NOT EDIT (§2.3)\n")
	if in.SettingsBlock != "" {
		sb.WriteString("server:\n")
		for _, line := range strings.Split(strings.TrimRight(in.SettingsBlock, "\n"), "\n") {
			sb.WriteString("  " + line + "\n")
		}
	} else {
		sb.WriteString("server:\n")
	}
	sb.WriteString("  interface: 0.0.0.0\n")
	sb.WriteString("  access-control: 0.0.0.0/0 allow\n")
	// 日志链路（§6）：统一落盘到挂载卷供 vector 采集；分级采样开关 P1（FR-E-05）
	sb.WriteString("  logfile: /var/log/unbound/unbound.log\n")
	sb.WriteString("  log-queries: yes\n")

	// 默认转发（forward-zone "."）
	writeForward(&sb, ".", in.DefaultFwd)

	// 条件转发规则（最长后缀由 unbound 按序匹配，这里保持声明顺序）
	for _, r := range in.Rules {
		writeForward(&sb, r.Domain, r.Addrs)
	}

	// 本地权威区（auth-zone + zonefile 由调用方落盘）
	for _, z := range in.AuthZones {
		fmt.Fprintf(&sb, "auth-zone:\n  name: %s\n", quoteName(z.Name))
		for _, rec := range z.Records {
			fmt.Fprintf(&sb, "  local-data: %s\n", quoteRec(rec))
		}
	}

	// 封禁 RPZ 区（zonefile 引用）
	for _, rz := range in.RpzZones {
		fmt.Fprintf(&sb, "rpz:\n  name: %s\n  zonefile: %s\n", quoteName(rz.Name), rz.ZonefilePath)
	}

	return sb.String()
}

func writeForward(sb *strings.Builder, domain string, addrs []string) {
	if len(addrs) == 0 {
		return
	}
	name := domain
	if name == "" || name == "." {
		name = "\".\""
	} else if !strings.HasPrefix(name, "\"") {
		name = quoteName(domain)
	}
	fmt.Fprintf(sb, "forward-zone:\n  name: %s\n", name)
	for _, a := range addrs {
		fmt.Fprintf(sb, "  forward-addr: %s\n", a)
	}
}

func quoteName(n string) string {
	if strings.HasPrefix(n, "\"") {
		return n
	}
	return "\"" + n + "\""
}

func quoteRec(r ZoneRecord) string {
	return fmt.Sprintf("\"%s %d IN %s %s\"", r.Name, r.TTL, r.Type, r.Data)
}
