package unbound

import (
	"context"
	"strings"
	"testing"
)

func TestBuildConf_五源合成(t *testing.T) {
	in := ConfInput{
		SettingsBlock: "cache-min-ttl: 0\nserve-expired: yes",
		DefaultFwd:    []string{"223.5.5.5:53"},
		Rules:         []ForwardRuleConf{{Domain: "corp.local.", Addrs: []string{"10.0.0.53:53"}}},
		AuthZones: []AuthZoneConf{{
			Name: "corp.local.",
			Records: []ZoneRecord{
				{Name: "www.corp.local.", Type: "A", TTL: 300, Data: "10.61.172.80"},
			},
		}},
		RpzZones: []RpzZoneConf{{Name: "students.rpz", ZonefilePath: "/var/lib/ipam/rpz/students.zone"}},
	}
	out := BuildConf(in)

	for _, want := range []string{
		"# Generated by ipam control-plane",
		"server:",
		"  cache-min-ttl: 0",
		"  serve-expired: yes",
		"forward-zone:\n  name: \".\"\n  forward-addr: 223.5.5.5@53",
		"forward-zone:\n  name: \"corp.local.\"\n  forward-addr: 10.0.0.53@53",
		"auth-zone:\n  name: \"corp.local.\"",
		"  local-data: \"www.corp.local. 300 IN A 10.61.172.80\"",
		"rpz:\n  name: \"students.rpz\"\n  zonefile: /var/lib/ipam/rpz/students.zone",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("missing %q in:\n%s", want, out)
		}
	}
}

func TestBuildConf_空输入仍产出合法骨架(t *testing.T) {
	out := BuildConf(ConfInput{})
	if !strings.HasPrefix(out, "# Generated") || !strings.Contains(out, "server:") {
		t.Fatalf("skeleton missing:\n%s", out)
	}
	if strings.Contains(out, "forward-zone:") {
		t.Fatal("no forward expected")
	}
}

func TestCheckConf_缺二进制返回不可用(t *testing.T) {
	e := ExecController{Bin: "/nonexistent"}
	if err := e.CheckConf(context.Background(), "/nonexistent.conf", "server:\n"); err == nil {
		t.Fatal("want ErrUnavailable")
	}
}
