/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dns/blocklists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询封禁名单库 */
        get: operations["listBlocklists"];
        put?: never;
        /** 创建名单库 */
        post: operations["createBlocklist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/blocklists/{listId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 订阅源同步（失败保留旧版）
         * @description kind=feed 时从 syncUrl 拉取域名列表；逐行解析+去重入库；版本+1。
         *     拉取/解析失败返回 502 且保留旧数据（K 风险项）。
         *     所需 scope 为 blocklist.write。
         */
        post: operations["syncBlocklist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/blocklists/{listId}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询名单条目 */
        get: operations["listBlocklistEntries"];
        put?: never;
        /** 添加条目 */
        post: operations["addBlocklistEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/policy-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询策略分组 */
        get: operations["listPolicyGroups"];
        put?: never;
        /** 创建策略分组（view 唯一） */
        post: operations["createPolicyGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/policy-groups/{groupId}/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 增量编译该分组的 RPZ zone 并单区刷新
         * @description 仅重写受影响策略组 zonefile（增量，§5.3）；去重后条目→zonefile→auth_zone_reload。
         *     返回编译结果与重载命令。所需 scope 为 blocklist.write。
         */
        post: operations["compilePolicyGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询本地区域 */
        get: operations["listDnsZones"];
        put?: never;
        /** 创建本地区域 */
        post: operations["createDnsZone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/zones/{zoneId}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询区域记录 */
        get: operations["listDnsRecords"];
        put?: never;
        /** 创建记录（变更触发 auth_zone_reload 单区刷新） */
        post: operations["createDnsRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/zones/{zoneId}/linked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 联动记录（只读，DHCP 双栈联动生成，§4.4） */
        get: operations["listLinkedRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/zones/{zoneId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出 zonefile（checkconf 校验过的静态区） */
        get: operations["exportDnsZone"];
        put?: never;
        post?: never;
        /** 删除区域（级联记录） */
        delete: operations["deleteDnsZone"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forward-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询条件转发规则 */
        get: operations["listForwardRules"];
        put?: never;
        /**
         * 创建条件转发规则（最长后缀优先）
         * @description 域名后缀与上游绑定；最长后缀优先匹配。dryRun=true 返回将执行的下发命令。
         *     所需 scope 为 dns.write。支持 Idempotency-Key。
         */
        post: operations["createForwardRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forward-rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除转发规则（forward_remove） */
        delete: operations["deleteForwardRule"];
        options?: never;
        head?: never;
        /** 更新转发规则（重新下发） */
        patch: operations["updateForwardRule"];
        trace?: never;
    };
    "/upstreams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询上游服务器（含探活状态）
         * @description 探活状态由 prober 周期维护（3 连败摘除/2 连胜回切）。
         */
        get: operations["listUpstreams"];
        put?: never;
        /**
         * 创建上游（触发 forward-zone 下发）
         * @description 落库后经 unbound 通道生效（forward_add）。scope 为 dns.write。
         */
        post: operations["createUpstream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upstreams/{upstreamId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除上游（forward_remove） */
        delete: operations["deleteUpstream"];
        options?: never;
        head?: never;
        /** 更新上游（重新下发） */
        patch: operations["updateUpstream"];
        trace?: never;
    };
    "/reservations/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 批量创建保留与静态绑定（CSV 语义，事务性）
         * @description 单请求内任一失败则整体回滚（无部分写入）+逐行失败明细。
         *     reserve=冻结不下发（excluded 语义）；bind=MAC 静态绑定（Kea host reservation）。
         *     所需 scope 为 reservation.write。支持 Idempotency-Key。
         */
        post: operations["bulkReservations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询资产登记
         * @description 按组织/关键字（MAC/使用人/部门）过滤；台账页资产页签数据源。
         */
        get: operations["listAssets"];
        /**
         * 创建/更新资产登记（MAC 幂等 upsert）
         * @description 以 MAC 为键幂等写入；换址（IP 变更）不影响备注。所需 scope 为 asset.write。支持 Idempotency-Key。
         */
        put: operations["upsertAsset"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{mac}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除资产登记
         * @description 按 MAC 删除。所需 scope 为 asset.write。
         */
        delete: operations["deleteAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询地址台账（六态矩阵）
         * @description 按组织/族/状态过滤；v4 逐地址返回，v6 返回子网级汇总。
         *     游标分页（cursor 取自上一页 nextCursor）。数据源=子网池∪绑定∪预留∪资产。
         */
        get: operations["listLedger"];
        put?: never;
        /**
         * 地址转保留（冻结不下发）
         * @description 生成 excluded 语义（pool kind=excluded 等价）并写 reservation(origin=manual, 无 MAC)。
         *     经 Kea 重新下发后生效。scope: ledger.write。支持 Idempotency-Key。
         */
        post: operations["reserveAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/bind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 地址转静态绑定（MAC 锚定）
         * @description 写 reservation(origin=manual, mac) 并经 Kea host reservation 下发；资产备注以 MAC 为键（§13.4）。
         *     scope: ledger.write。支持 Idempotency-Key。
         */
        post: operations["bindStatic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subnets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询子网列表
         * @description 支持 orgId / family 过滤；用于台账与 DHCP 管理页。
         */
        get: operations["listSubnets"];
        put?: never;
        /**
         * 创建子网与地址池
         * @description 落库后经 engine/kea 三步走下发（生成→config-set staged 校验→生效，失败回滚上一 revision，§2.2）。
         *     dryRun=true 仅生成校验不下发；支持 Idempotency-Key。scope: subnet.write。
         */
        post: operations["createSubnet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subnets/{subnetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除子网（级联池）
         * @description 级联删除地址池；若存在租约/模板引用返回 409。所需 scope 为 subnet.write。标记 x-risk-level destructive。
         */
        delete: operations["deleteSubnet"];
        options?: never;
        head?: never;
        /**
         * 更新子网（改名/调整池）
         * @description 变更同样经 Kea 三步走下发；失败回滚并返回 503。所需 scope 为 subnet.write。
         */
        patch: operations["updateSubnet"];
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询组织分组树
         * @description 返回完整嵌套组织树（多级自定义分组，§13.4 主数据）。
         *     用途：地址台账/DHCP 子网页左侧组织树、日志中心按组织展开 CIDR 过滤。
         */
        get: operations["listOrgTree"];
        put?: never;
        /**
         * 创建组织分组节点
         * @description 在指定父节点下创建；parentId 缺省创建根。
         *     所需 scope：org.write。同父下重名将返回 409 ORG_NAME_DUP。
         */
        post: operations["createOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除空组织节点
         * @description 删除保护：存在子节点、或仍被子网/资产引用时返回 409 ORG_IN_USE（§13.4 删除保护）。
         *     所需 scope：org.write。危险操作：x-risk-level destructive。
         */
        delete: operations["deleteOrg"];
        options?: never;
        head?: never;
        /**
         * 改名与/或移动组织节点
         * @description 移动目标不得为自身或其子孙（409 ORG_CYCLE）；移动将级联更新整棵子树的物化路径。
         *     所需 scope：org.write。支持 Idempotency-Key。
         */
        patch: operations["updateOrg"];
        trace?: never;
    };
    "/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询控制面系统信息
         * @description 返回控制面版本、运行时与就绪状态。
         *     用途：仪表盘「服务健康」卡片数据源与负载均衡探活。
         *     所需权限：匿名可读（登录页即需探活）；管理类端点默认 bearerAuth。
         */
        get: operations["getSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SystemInfo: {
            /** @description 服务标识，固定值 ipam-control-plane */
            name: string;
            /** @description 语义化版本号，构建期经 ldflags 注入 */
            version: string;
            /** @description 编译所用 Go 运行时版本（runtime.Version()） */
            goVersion: string;
            /**
             * Format: date-time
             * @description 服务端当前时间（UTC，RFC3339）
             */
            now: string;
            /** @description 关键依赖（PostgreSQL）可达则为 true；false 时仪表盘服务健康亮黄 */
            ready: boolean;
        };
        /** @description 组织分组节点（多级自定义树，主数据，§13.4）。 */
        OrgNode: {
            /**
             * Format: uuid
             * @description 节点 ID
             */
            id: string;
            /** @description 父节点 ID；根为 null */
            parentId: string | null;
            /** @description 名称（同父下唯一），如 A公司/B部门 */
            name: string;
            /** @description 物化路径 "/<id>/<id>"，用于子树整体检索与组织→CIDR 展开 */
            path: string;
        };
        OrgTreeNode: {
            /** Format: uuid */
            id: string;
            parentId: string | null;
            name: string;
            path: string;
            children: components["schemas"]["OrgTreeNode"][];
        };
        OrgCreate: {
            /** @description 父节点 ID；缺省创建根节点 */
            parentId?: string | null;
            /** @description 同父下唯一名称 */
            name: string;
        };
        /** @description 改名与/或移动；移动目标不得为自身或其子孙（409 ORG_CYCLE）。 */
        OrgUpdate: {
            name?: string;
            parentId?: string | null;
        };
        /** @description 子网（IPv4/IPv6，挂组织树；FR-C、§13.4）。 */
        Subnet: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description 所属组织节点（组织→子网→租约/台账关联链起点）
             */
            orgId: string;
            name: string;
            /** @enum {integer} */
            family: 4 | 6;
            /** @description 如 10.61.172.0/24 或 2406:172::/64 */
            cidr: string;
            pools: components["schemas"]["AddressPool"][];
            /** @description 下发 Kea 后的 subnet-id（引擎回写） */
            keaSubnetId?: number;
            description?: string;
        };
        AddressPool: {
            startAddr: string;
            endAddr: string;
            /**
             * @description excluded=保留段（§13.4 冻结不下发）
             * @default dynamic
             * @enum {string}
             */
            kind: "dynamic" | "pd" | "excluded";
        };
        SubnetCreate: {
            /** Format: uuid */
            orgId: string;
            name: string;
            /** @enum {integer} */
            family: 4 | 6;
            cidr: string;
            pools?: components["schemas"]["AddressPool"][];
            /**
             * @description true 时仅生成并校验 Kea 配置，不实际下发（§12.2 约定 5）
             * @default false
             */
            dryRun: boolean;
            description?: string;
        };
        SubnetUpdate: {
            name?: string;
            pools?: components["schemas"]["AddressPool"][];
            description?: string;
        };
        /** @description 列表（可按组织/族过滤） */
        SubnetList: {
            items: components["schemas"]["Subnet"][];
            total?: number;
        };
        /**
         * @description 地址六态（§13.4 颜色规范）：在线=租约活跃近似（绿）/空闲（灰蓝）/保留冻结（黄）/静态绑定（蓝）/过期宽限（橙）/冲突（红）
         * @enum {string}
         */
        LedgerState: "online" | "available" | "reserved" | "static" | "grace" | "conflict";
        LedgerRow: {
            /** @description IPv4 逐地址；IPv6 为子网级汇总行（/64 前缀） */
            address: string;
            /** @enum {integer} */
            family: 4 | 6;
            state: components["schemas"]["LedgerState"];
            /** @description 绑定/租约关联 MAC（六态中 online/static/grace/conflict 通常有） */
            mac?: string;
            hostname?: string;
            /** @description 资产登记使用人（asset 表，以 MAC 为键） */
            owner?: string;
            /**
             * Format: date-time
             * @description 租约到期时间（在线态展示）
             */
            leaseExpiry?: string;
            /** Format: uuid */
            subnetId?: string;
            /** @description 游标键："{family}:{address}"，排序稳定 */
            poolIndex?: string;
        };
        LedgerPage: {
            items: components["schemas"]["LedgerRow"][];
            /** @description 下一页游标；空=已到尾页 */
            nextCursor?: string;
            /** @description 满足过滤的总行数（v4 逐地址计数） */
            total?: number;
        };
        ReserveRequest: {
            /** Format: uuid */
            subnetId: string;
            address: string;
            /** @description 保留原因（审计） */
            reason?: string;
        };
        BindRequest: {
            /** Format: uuid */
            subnetId: string;
            address: string;
            /** @description 归一化小写冒号格式 */
            mac: string;
            hostname?: string;
        };
        /** @description 资产登记（MAC 为身份键，换址备注不丢；§13.4 资产登记）。 */
        Asset: {
            /** @description 归一化小写冒号格式（aa:bb:cc:dd:ee:ff） */
            mac: string;
            /**
             * Format: uuid
             * @description 所属组织节点（资产→组织→日志关联链）
             */
            orgId?: string;
            /** @description 使用人员 */
            owner: string;
            dept?: string;
            note?: string;
            tags?: string[];
        };
        /** @description 创建/更新（以 MAC 幂等 upsert） */
        AssetUpsert: {
            mac: string;
            /** Format: uuid */
            orgId?: string;
            owner: string;
            dept?: string;
            note?: string;
            tags?: string[];
        };
        AssetList: {
            items: components["schemas"]["Asset"][];
            total?: number;
        };
        /** @description 批量导入单行（CSV 语义；kind ∈ reserve|bind）。 */
        ReservationBulkEntry: {
            /**
             * @description reserve=冻结保留（无 MAC）；bind=静态绑定（需 MAC）
             * @enum {string}
             */
            kind: "reserve" | "bind";
            address: string;
            /** @description kind=bind 必填（归一化小写冒号格式） */
            mac?: string;
            reason?: string;
        };
        ReservationBulkRequest: {
            /** Format: uuid */
            subnetId: string;
            entries: components["schemas"]["ReservationBulkEntry"][];
        };
        /** @description 批量结果（全部或全不：任一失败整体回滚）。 */
        ReservationBulkResult: {
            /** @description 是否全部成功（false=整体回滚，无任何写入） */
            ok: boolean;
            /** @description 成功应用条数（ok=true 时=entries 数） */
            applied: number;
            failures: {
                /** @description 原始行号（1 起） */
                line: number;
                /** @description 失败原因（占用/非法 MAC/地址越池等） */
                reason: string;
            }[];
        };
        /** @description DNS 上游服务器（FR-B-01；探活状态灯数据源 F-R4）。 */
        Upstream: {
            /** Format: uuid */
            id: string;
            name: string;
            addrs: string[];
            /** @enum {string} */
            protocol: "udp" | "tcp" | "dot";
            weight: number;
            enabled: boolean;
            /** @description 探活状态（prober 维护） */
            health: {
                up?: boolean;
                rttMs?: number;
                consecutiveFails?: number;
                /** Format: date-time */
                lastCheck?: string;
            };
        };
        UpstreamCreate: {
            name: string;
            addrs: string[];
            /**
             * @default udp
             * @enum {string}
             */
            protocol: "udp" | "tcp" | "dot";
            /** @default 1 */
            weight: number;
            /** @default true */
            enabled: boolean;
        };
        UpstreamUpdate: {
            name?: string;
            addrs?: string[];
            /** @enum {string} */
            protocol?: "udp" | "tcp" | "dot";
            weight?: number;
            enabled?: boolean;
        };
        UpstreamList: {
            items: components["schemas"]["Upstream"][];
            total?: number;
        };
        /** @description 条件转发规则（域名后缀→指定上游；最长后缀优先，FR-B-02）。 */
        ForwardRule: {
            /** Format: uuid */
            id: string;
            /** @description 域名后缀（如 corp.local. 或 . 表示默认）；最长匹配优先 */
            domain: string;
            /** @description 该规则使用的上游（引用 /upstreams） */
            upstreamIds: string[];
            enabled: boolean;
            note?: string;
        };
        ForwardRuleCreate: {
            domain: string;
            upstreamIds: string[];
            /** @default true */
            enabled: boolean;
            note?: string;
            /**
             * @description true 时仅生成 forward_add 命令串并返回，不实际下发
             * @default false
             */
            dryRun: boolean;
        };
        /** @description dryRun 输出（生成的下发命令预览） */
        ForwardRuleDryRun: {
            /** @description 如 ["unbound-control forward_add corp.local. 10.0.0.53@53"] */
            commands: string[];
        };
        ForwardRuleList: {
            items: components["schemas"]["ForwardRule"][];
            total?: number;
        };
        /** @description 本地区域（auth-zone/local-zone，§13.4 解析记录）。 */
        DnsZone: {
            /** Format: uuid */
            id: string;
            /** @description FQDN 如 corp.local. */
            name: string;
            /** @enum {string} */
            kind: "auth" | "local";
            enabled: boolean;
        };
        DnsZoneCreate: {
            name: string;
            /**
             * @default auth
             * @enum {string}
             */
            kind: "auth" | "local";
        };
        /** @description 解析记录。 */
        DnsRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            zoneId: string;
            /** @description 相对名（www）或 FQDN */
            name: string;
            /** @enum {string} */
            recType: "A" | "AAAA" | "CNAME" | "PTR";
            ttl: number;
            /** @description 记录数据（A=IP/CNAME=目标/PTR=域名） */
            rdata: string;
            /** @default true */
            enabled: boolean;
        };
        DnsRecordCreate: {
            name: string;
            /** @enum {string} */
            recType: "A" | "AAAA" | "CNAME" | "PTR";
            /** @default 300 */
            ttl: number;
            rdata: string;
            /** @default true */
            enabled: boolean;
        };
        /** @description 联动记录（只读，来自 DHCP 双栈联动自动生成，§4.4）。 */
        LinkedRecord: {
            name: string;
            /** @enum {string} */
            recType: "A" | "AAAA" | "PTR";
            rdata: string;
            /** @description 来源终端 MAC（联调查证） */
            mac?: string;
        };
        DnsZoneList: {
            items: components["schemas"]["DnsZone"][];
            total?: number;
        };
        DnsRecordList: {
            items: components["schemas"]["DnsRecord"][];
            total?: number;
        };
        /** @description 封禁名单库（内置/自定义/订阅源，FR-B-11~14、D13）。 */
        Blocklist: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            kind: "builtin" | "custom" | "feed";
            /** @description kind=feed 的订阅地址(HTTP) */
            syncUrl?: string | null;
            /** Format: date-time */
            lastSync?: string | null;
            /** @description 版本号（每次同步+1，回滚用） */
            version: number;
        };
        BlocklistCreate: {
            name: string;
            /**
             * @default custom
             * @enum {string}
             */
            kind: "builtin" | "custom" | "feed";
            syncUrl?: string | null;
        };
        /** @description 名单条目（RPZ 语义）。 */
        BlocklistEntry: {
            /** Format: uuid */
            listId: string;
            /** @enum {string} */
            triggerType: "qname" | "response_ip";
            /** @description 域名（*.bad.com 通配）或 CIDR */
            pattern: string;
            /**
             * @default nxdomain
             * @enum {string}
             */
            action: "nxdomain" | "drop" | "tcp_only" | "redirect";
            /** @description action=redirect 的提示页记录名 */
            redirectTarget?: string | null;
            /** @description 拦截报表分类标签 */
            category?: string;
        };
        BlocklistEntryCreate: {
            /** @enum {string} */
            triggerType: "qname" | "response_ip";
            pattern: string;
            /** @enum {string} */
            action: "nxdomain" | "drop" | "tcp_only" | "redirect";
            redirectTarget?: string | null;
            category?: string;
        };
        /** @description 订阅源同步结果。 */
        BlocklistSyncResult: {
            /** Format: uuid */
            listId: string;
            version: number;
            /** @description 本次新增去重后条数 */
            added: number;
            /** @description 同步后库内条数 */
            total: number;
        };
        BlocklistList: {
            items: components["schemas"]["Blocklist"][];
            total?: number;
        };
        BlocklistEntryList: {
            items: components["schemas"]["BlocklistEntry"][];
            total?: number;
        };
        /** @description 封禁策略分组（view×网段×名单×时段，FR-B-15/16、§5.1）。 */
        PolicyGroup: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description 对应 unbound view 名（唯一） */
            viewName: string;
            /** @description 匹配来源网段 */
            cidrs: string[];
            /** @description 生效名单集合(白单优先) */
            listIds: string[];
            /** @description 时段表（cron 展开） */
            schedule?: Record<string, never> | null;
        };
        PolicyGroupCreate: {
            name: string;
            viewName: string;
            cidrs: string[];
            listIds: string[];
            schedule?: Record<string, never> | null;
        };
        /** @description RPZ 增量编译结果。 */
        RpzCompileResult: {
            /** @description rpz zone 名（view_name.rpz） */
            zone: string;
            /** @description 去重后条目数 */
            entries: number;
            /** @description zonefile 路径 */
            path: string;
            /** @description 如 unbound-control auth_zone_reload students.rpz */
            reloadCommand: string;
        };
        /** @description RFC 9457 问题详情。type/code 字段供机器判读，AI agent 可据此自纠重试（§12.2 约定 4）。 */
        Problem: {
            /** @description 问题类型 URI，稳定不变供程序匹配 */
            type: string;
            /** @description 人类可读摘要 */
            title: string;
            /** @description HTTP 状态码 */
            status: number;
            /** @description 具体原因说明（不含敏感信息） */
            detail?: string;
            /** @description 业务错误码（如 PLATFORM_DB_DOWN），枚举随端点文档化 */
            code?: string;
            /** @description 出错请求的路径 */
            instance?: string;
        };
    };
    responses: {
        /** @description 错误响应（RFC 9457 Problem Details） */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 子网列表 */
        SubnetListOK: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SubnetList"];
            };
        };
        /** @description 创建成功（含 dryRun 结果） */
        SubnetCreated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Subnet"];
            };
        };
        /** @description 子网仍被引用（如租约/模板）或 Kea 下发失败回滚（409/503） */
        SubnetInUseError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    type: string;
                    title: string;
                    status: number;
                    detail?: string;
                    code?: string;
                    instance?: string;
                };
            };
        };
        /** @description 更新成功 */
        SubnetUpdated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Subnet"];
            };
        };
        /** @description 组织树（嵌套结构，listOrgTree） */
        OrgTree: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OrgTreeNode"][];
            };
        };
        /** @description 创建成功 */
        OrgCreated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OrgNode"];
            };
        };
        /** @description 资源不存在（404） */
        NotFound404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": unknown;
            };
        };
        /** @description 节点仍被引用或含子节点，禁止删除（409） */
        OrgInUseError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": unknown;
            };
        };
        /** @description 更新成功 */
        OrgUpdated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OrgNode"];
            };
        };
    };
    parameters: {
        /** @description 组织节点 ID */
        OrgId: string;
        SubnetId: string;
        /** @description 子网 ID */
        SubnetIdParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBlocklists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 名单列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlocklistList"];
                    examples: unknown;
                };
            };
        };
    };
    createBlocklist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlocklistCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blocklist"];
                };
            };
        };
    };
    syncBlocklist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 同步完成 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlocklistSyncResult"];
                };
            };
            /** @description 订阅源不可达/解析失败（旧版保留） */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                    examples: unknown;
                };
            };
        };
    };
    listBlocklistEntries: {
        parameters: {
            query?: {
                /** @description 关键字（pattern 模糊） */
                q?: string;
            };
            header?: never;
            path: {
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 条目列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlocklistEntryList"];
                    examples: unknown;
                };
            };
        };
    };
    addBlocklistEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlocklistEntryCreate"];
            };
        };
        responses: {
            /** @description 已添加 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlocklistEntry"];
                };
            };
        };
    };
    listPolicyGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分组列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PolicyGroup"][];
                    };
                    examples: unknown;
                };
            };
        };
    };
    createPolicyGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyGroupCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyGroup"];
                };
            };
        };
    };
    compilePolicyGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 编译完成 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RpzCompileResult"];
                };
            };
        };
    };
    listDnsZones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 区域列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsZoneList"];
                    examples: unknown;
                };
            };
        };
    };
    createDnsZone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DnsZoneCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsZone"];
                };
            };
        };
    };
    listDnsRecords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zoneId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 记录列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsRecordList"];
                    examples: unknown;
                };
            };
        };
    };
    createDnsRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zoneId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DnsRecordCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsRecord"];
                };
            };
        };
    };
    listLinkedRecords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zoneId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 联动记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["LinkedRecord"][];
                    };
                    examples: unknown;
                };
            };
        };
    };
    exportDnsZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zoneId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description zonefile 文本（text/plain） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                    examples: unknown;
                };
            };
        };
    };
    deleteDnsZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zoneId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listForwardRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 规则列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForwardRuleList"];
                    examples: unknown;
                };
            };
        };
    };
    createForwardRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForwardRuleCreate"];
            };
        };
        responses: {
            /** @description dryRun 预览 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForwardRuleDryRun"];
                };
            };
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForwardRule"];
                };
            };
        };
    };
    deleteForwardRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateForwardRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    upstreamIds?: string[];
                    enabled?: boolean;
                    note?: string;
                };
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForwardRule"];
                };
            };
        };
    };
    listUpstreams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 上游列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamList"];
                    examples: unknown;
                };
            };
        };
    };
    createUpstream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpstreamCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upstream"];
                };
            };
        };
    };
    deleteUpstream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upstreamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateUpstream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upstreamId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpstreamUpdate"];
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upstream"];
                };
            };
        };
    };
    bulkReservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationBulkRequest"];
            };
        };
        responses: {
            /** @description 批量结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationBulkResult"];
                    examples: unknown;
                };
            };
            /** @description Kea 下发失败（已整体回滚） */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                    examples: unknown;
                };
            };
        };
    };
    listAssets: {
        parameters: {
            query?: {
                orgId?: string;
                /** @description 关键字：MAC/owner/dept 模糊匹配 */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资产列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetList"];
                    examples: unknown;
                };
            };
        };
    };
    upsertAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetUpsert"];
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                    examples: unknown;
                };
            };
        };
    };
    deleteAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mac: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 资产不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listLedger: {
        parameters: {
            query?: {
                orgId?: string;
                family?: 4 | 6;
                state?: components["schemas"]["LedgerState"];
                cursor?: string;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 台账页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerPage"];
                    examples: unknown;
                };
            };
        };
    };
    reserveAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveRequest"];
            };
        };
        responses: {
            /** @description 已保留 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 地址已被占用（绑定/在线） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                    examples: unknown;
                };
            };
        };
    };
    bindStatic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindRequest"];
            };
        };
        responses: {
            /** @description 已绑定 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 地址已被占用 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                };
            };
        };
    };
    listSubnets: {
        parameters: {
            query?: {
                orgId?: string;
                family?: 4 | 6;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SubnetListOK"];
        };
    };
    createSubnet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubnetCreate"];
            };
        };
        responses: {
            201: components["responses"]["SubnetCreated"];
            503: components["responses"]["SubnetInUseError"];
        };
    };
    deleteSubnet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 子网 ID */
                subnetId: components["parameters"]["SubnetIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 子网不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                };
            };
            /** @description 仍被引用 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                    examples: unknown;
                };
            };
        };
    };
    updateSubnet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 子网 ID */
                subnetId: components["parameters"]["SubnetIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubnetUpdate"];
            };
        };
        responses: {
            200: components["responses"]["SubnetUpdated"];
            /** @description 子网不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                };
            };
            503: components["responses"]["SubnetInUseError"];
        };
    };
    listOrgTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OrgTree"];
        };
    };
    createOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgCreate"];
            };
        };
        responses: {
            201: components["responses"]["OrgCreated"];
            /** @description 同父重名 / 父不存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    deleteOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 组织节点 ID */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound404"];
            409: components["responses"]["OrgInUseError"];
        };
    };
    updateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 组织节点 ID */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgUpdate"];
            };
        };
        responses: {
            200: components["responses"]["OrgUpdated"];
            404: components["responses"]["NotFound404"];
            /** @description 目标父为自身子孙（ORG_CYCLE） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    getSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 系统信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
            500: components["responses"]["Problem"];
        };
    };
}
