/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登录颁发访问令牌（PoC 直通）
         * @description 校验固定账号（admin / IPAM_POC_PASSWORD），签发 HMAC 形状 accessToken。
         *     正式多用户/JWT/Bot Token 由 M5-002 替换（§12.3），响应结构保持兼容。
         */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/user/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前登录用户信息
         * @description 按请求携带的 Authorization Bearer 令牌解析身份；无效/缺失返回 401。
         *     同时以 /user/info（vben 前端约定路径）提供同一资源，operationId=getAuthUserInfoAlias。
         */
        get: operations["getAuthUserInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前登录用户信息（/user/info 别名）
         * @description 与 getAuthUserInfo 同一资源：vben 底座 fetchUserInfo 约定路径为 GET /user/info，
         *     本别名保证底座升级零侵入。响应与 AuthUserInfo 完全一致。
         */
        get: operations["getAuthUserInfoAlias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前用户权限码
         * @description 权限码与 scope 同源（§13.2）；PoC 阶段返回空数组=不启用按钮级权限。
         */
        get: operations["listAuthCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 注销当前会话
         * @description PoC 令牌为无状态签名，服务端无可撤销状态；端点仅作前端登出闭环。
         */
        post: operations["logoutAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 仪表盘单请求聚合快照
         * @description 一级菜单「仪表盘」全部卡片数据的单端点聚合（≤1s 预算）：今日活跃终端与 24h 趋势、
         *     新增/离线终端、服务健康灯（PG/CH/kea/unbound）、DNS QPS 与拦截量、池利用率 Top5、联动成功率。
         *     指标口径见各字段 description；不可测量项返回 null 而非伪造值。
         *     数据源：ClickHouse logs（复用 §6 查询网关）+ PostgreSQL（子网池/联动绑定）+ 进程内探针。
         */
        get: operations["getDashboardOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询日志（组合过滤+游标分页）
         * @description 日志中心检索（FR-E-04）：时间窗必填，type/mac/ip/domain/action 组合过滤；
         *     orgId 按组织维度展开（子树 CIDR ∪ 组内资产 MAC，§13.4 关联链）。
         *     游标分页：cursor 取自上一页 nextCursor，排序键 (ts, client_mac, domain) 保证确定性。
         *     数据源 ClickHouse logs 宽表（§6）。
         */
        get: operations["listLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/tail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 实时日志流（SSE live-tail）
         * @description 近实时日志通道（F-R7）：text/event-stream 持续推送新事件，服务端 500ms 轮询，
         *     延迟 ≤2s；15s 心跳注释保活；Last-Event-ID 头（或 from 参数）断线续传。
         *     event=id（(ts,client_mac,domain) 元组编码，可直接作续传位点）；data=LogRow JSON。
         *     过滤条件与 /logs 一致但不分页；from 缺省=连接建立时刻。
         */
        get: operations["streamLogTail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TopN 域名与客户端
         * @description 物化视图聚合支撑（§6/§8：5000 终端天量 ≤3s）。by=domain 返回查询域名 TopN，
         *     by=client 返回客户端 MAC TopN；过滤条件同 /logs（组织维度同样支持）。
         */
        get: operations["listLogTop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/qps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * QPS 时序曲线
         * @description 按 intervalSec 分桶计数（toStartOfInterval），返回时间升序的时序点。
         *     供日志中心曲线与仪表盘 DNS QPS 卡片消费（§13.4）。
         */
        get: operations["getLogQps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询操作审计
         * @description 管理员操作审计检索（FR-F）：actor 类型/动作/资源子串/时间窗组合过滤，
         *     游标分页按 (ts DESC, id DESC) 稳定翻页。仅变更类请求（POST/PATCH/DELETE）入库；
         *     数据源 PostgreSQL operation_audit 表，token 身份在 M5 JWT 接入后填充（§12.3）。
         */
        get: operations["listOperationAudits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 导出日志 CSV
         * @description 过滤条件与 /logs 一致；按 ts 倒序导出 CSV（RFC 4180，UTF-8 含 BOM，Excel 可直接打开），
         *     exportLimit 上限 10000 行。scope 需 logs.export（审计留痕）。
         */
        get: operations["exportLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/conf/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 应用五源合成 unbound.conf（渲染→checkconf→原子落盘→reload）
         * @description 从各域仓储聚合上游/转发/解析记录/封禁/参数五源，合成完整 unbound.conf，
         *     经 checkconf 校验后原子替换并 reload。校验失败返回 400 且运行态不变。
         *     所需 scope 为 dns.write。
         */
        post: operations["applyDnsConf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询 DNS 行为参数（缓存+安全）
         * @description 返回当前生效的缓存与安全参数；参数变更经 unbound.conf 重渲染+checkconf+reload 三步走。
         */
        get: operations["getDnsSettings"];
        /**
         * 更新 DNS 行为参数（渲染→checkconf→reload）
         * @description 校验失败返回 400 且不改动运行配置（checkconf 失败即回滚）。所需 scope 为 dns.write。
         */
        put: operations["updateDnsSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/settings/ttl-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询每域名 TTL 覆盖列表
         * @description F-R3——对 DDNS/CDN 敏感域名单独设置较小 TTL，覆盖全局缓存策略。
         */
        get: operations["listTtlOverrides"];
        /**
         * 设置或更新域名 TTL 覆盖（reload 生效）
         * @description 以域名为键幂等写入，reload 后生效。所需 scope 为 dns.write。
         */
        put: operations["upsertTtlOverride"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/cache/flush": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 清空缓存（全部或指定 zone）
         * @description 经 unbound-control flush 或 flush_zone 执行，zone 缺省为全部清空。所需 scope 为 dns.write。
         */
        post: operations["flushCache"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/blocklists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询封禁名单库
         * @description 返回内置/自定义/订阅三类名单及版本与最近同步时间。
         */
        get: operations["listBlocklists"];
        put?: never;
        /**
         * 创建名单库
         * @description kind=feed 时必须提供 syncUrl；后续经 sync 端点拉取。scope 为 blocklist.write。
         */
        post: operations["createBlocklist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/blocklists/{listId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 订阅源同步（失败保留旧版）
         * @description 仅对 kind=feed 生效：从 syncUrl 拉取域名列表，逐行解析+去重入库，版本+1。
         *     拉取/解析失败返回 502 且保留旧数据（风险项）。所需 scope 为 blocklist.write。
         */
        post: operations["syncBlocklist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/blocklists/{listId}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询名单条目
         * @description 支持 pattern 关键字过滤；返回 RPZ 动作与分类标签。
         */
        get: operations["listBlocklistEntries"];
        put?: never;
        /**
         * 添加条目
         * @description 同名单内 pattern 去重；动作映射见 §5.2。scope 为 blocklist.write。
         */
        post: operations["addBlocklistEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/policy-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询策略分组
         * @description 返回 view×网段×名单×时段 的全部策略组（§5.1）。
         */
        get: operations["listPolicyGroups"];
        put?: never;
        /**
         * 创建策略分组（view 唯一）
         * @description view_name 全局唯一；创建后调用 compile 生成 RPZ zone。scope 为 blocklist.write。
         */
        post: operations["createPolicyGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/policy-groups/{groupId}/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 增量编译该分组的 RPZ zone 并单区刷新
         * @description 仅重写受影响策略组 zonefile（增量，§5.3）；去重后条目→zonefile→auth_zone_reload。
         *     返回编译结果与重载命令。所需 scope 为 blocklist.write。
         */
        post: operations["compilePolicyGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询本地区域
         * @description 返回 auth/local 两类区域；记录经各 zone 的 records 端点管理。
         */
        get: operations["listDnsZones"];
        put?: never;
        /**
         * 创建本地区域
         * @description 区域名全局唯一（尾点容错）；创建后可添加解析记录。所需 scope 为 dns.write。
         */
        post: operations["createDnsZone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/zones/{zoneId}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询区域记录
         * @description 返回该区域全部解析记录，含禁用项，前端可按需过滤展示。
         */
        get: operations["listDnsRecords"];
        put?: never;
        /**
         * 创建记录（触发 auth_zone_reload 单区刷新）
         * @description 同 zone 内 name 与 type 组合唯一；rdata 按类型校验；创建后单区刷新不动整进程。scope 为 dns.write。
         */
        post: operations["createDnsRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/zones/{zoneId}/linked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 联动记录（只读）
         * @description 返回由 DHCP 双栈联动自动生成的 A 与 AAAA 记录（§4.4），只读不可编辑。
         */
        get: operations["listLinkedRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns/zones/{zoneId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 导出 zonefile（checkconf 校验过的静态区）
         * @description 返回以 ORIGIN 起头的标准 zonefile 文本，供 auth_zone_reload 使用。
         */
        get: operations["exportDnsZone"];
        put?: never;
        post?: never;
        /**
         * 删除区域（级联记录）
         * @description 级联删除区域内全部解析记录并刷新 unbound。scope 为 dns.write。
         */
        delete: operations["deleteDnsZone"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forward-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询条件转发规则
         * @description 返回全部转发规则含启用状态；最长后缀优先语义见 FR-B-02。
         */
        get: operations["listForwardRules"];
        put?: never;
        /**
         * 创建条件转发规则（最长后缀优先）
         * @description 域名后缀与上游绑定；最长后缀优先匹配。dryRun=true 返回将执行的下发命令。
         *     所需 scope 为 dns.write。支持 Idempotency-Key。
         */
        post: operations["createForwardRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forward-rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除转发规则（forward_remove）
         * @description 删除后立即从 unbound 摘除对应 forward-zone。所需 scope 为 dns.write。
         */
        delete: operations["deleteForwardRule"];
        options?: never;
        head?: never;
        /**
         * 更新转发规则（重新下发）
         * @description 变更上游集合或启停后自动重下发；失败返回 503 UNBOUND_DOWN。所需 scope 为 dns.write。
         */
        patch: operations["updateForwardRule"];
        trace?: never;
    };
    "/upstreams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询上游服务器（含探活状态）
         * @description 探活状态由 prober 周期维护（3 连败摘除/2 连胜回切）。
         */
        get: operations["listUpstreams"];
        put?: never;
        /**
         * 创建上游（触发 forward-zone 下发）
         * @description 落库后经 unbound 通道生效（forward_add）。scope 为 dns.write。
         */
        post: operations["createUpstream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upstreams/{upstreamId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除上游（forward_remove）
         * @description 从 forward-zone 移除并停止探测；历史 RTT 记录保留用于审计。所需 scope 为 dns.write。
         */
        delete: operations["deleteUpstream"];
        options?: never;
        head?: never;
        /**
         * 更新上游（重新下发）
         * @description 变更后触发 forward-zone 重收敛；探活状态由 prober 刷新。所需 scope 为 dns.write。
         */
        patch: operations["updateUpstream"];
        trace?: never;
    };
    "/reservations/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 批量创建保留与静态绑定（CSV 语义，事务性）
         * @description 单请求内任一失败则整体回滚（无部分写入）+逐行失败明细。
         *     reserve=冻结不下发（excluded 语义）；bind=MAC 静态绑定（Kea host reservation）。
         *     所需 scope 为 reservation.write。支持 Idempotency-Key。
         */
        post: operations["bulkReservations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询资产登记
         * @description 按组织/关键字（MAC/使用人/部门）过滤；台账页资产页签数据源。
         */
        get: operations["listAssets"];
        /**
         * 创建/更新资产登记（MAC 幂等 upsert）
         * @description 以 MAC 为键幂等写入；换址（IP 变更）不影响备注。所需 scope 为 asset.write。支持 Idempotency-Key。
         */
        put: operations["upsertAsset"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{mac}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除资产登记
         * @description 按 MAC 删除。所需 scope 为 asset.write。
         */
        delete: operations["deleteAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询地址台账（六态矩阵）
         * @description 按组织/族/状态过滤；v4 逐地址返回，v6 返回子网级汇总。
         *     游标分页（cursor 取自上一页 nextCursor）。数据源=子网池∪绑定∪预留∪资产。
         */
        get: operations["listLedger"];
        put?: never;
        /**
         * 地址转保留（冻结不下发）
         * @description 生成 excluded 语义（pool kind=excluded 等价）并写 reservation(origin=manual, 无 MAC)。
         *     经 Kea 重新下发后生效。scope: ledger.write。支持 Idempotency-Key。
         */
        post: operations["reserveAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ledger/bind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 地址转静态绑定（MAC 锚定）
         * @description 写 reservation(origin=manual, mac) 并经 Kea host reservation 下发；资产备注以 MAC 为键（§13.4）。
         *     scope: ledger.write。支持 Idempotency-Key。
         */
        post: operations["bindStatic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subnets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询子网列表
         * @description 支持 orgId / family 过滤；用于台账与 DHCP 管理页。
         */
        get: operations["listSubnets"];
        put?: never;
        /**
         * 创建子网与地址池
         * @description 落库后经 engine/kea 三步走下发（生成→config-set staged 校验→生效，失败回滚上一 revision，§2.2）。
         *     dryRun=true 仅生成校验不下发；支持 Idempotency-Key。scope: subnet.write。
         */
        post: operations["createSubnet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subnets/{subnetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除子网（级联池）
         * @description 级联删除地址池；若存在租约/模板引用返回 409。所需 scope 为 subnet.write。标记 x-risk-level destructive。
         */
        delete: operations["deleteSubnet"];
        options?: never;
        head?: never;
        /**
         * 更新子网（改名/调整池）
         * @description 变更同样经 Kea 三步走下发；失败回滚并返回 503。所需 scope 为 subnet.write。
         */
        patch: operations["updateSubnet"];
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询组织分组树
         * @description 返回完整嵌套组织树（多级自定义分组，§13.4 主数据）。
         *     用途：地址台账/DHCP 子网页左侧组织树、日志中心按组织展开 CIDR 过滤。
         */
        get: operations["listOrgTree"];
        put?: never;
        /**
         * 创建组织分组节点
         * @description 在指定父节点下创建；parentId 缺省创建根。
         *     所需 scope：org.write。同父下重名将返回 409 ORG_NAME_DUP。
         */
        post: operations["createOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除空组织节点
         * @description 删除保护：存在子节点、或仍被子网/资产引用时返回 409 ORG_IN_USE（§13.4 删除保护）。
         *     所需 scope：org.write。危险操作：x-risk-level destructive。
         */
        delete: operations["deleteOrg"];
        options?: never;
        head?: never;
        /**
         * 改名与/或移动组织节点
         * @description 移动目标不得为自身或其子孙（409 ORG_CYCLE）；移动将级联更新整棵子树的物化路径。
         *     所需 scope：org.write。支持 Idempotency-Key。
         */
        patch: operations["updateOrg"];
        trace?: never;
    };
    "/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询控制面系统信息
         * @description 返回控制面版本、运行时与就绪状态。
         *     用途：仪表盘「服务健康」卡片数据源与负载均衡探活。
         *     所需权限：匿名可读（登录页即需探活）；管理类端点默认 bearerAuth。
         */
        get: operations["getSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SystemInfo: {
            /** @description 服务标识，固定值 ipam-control-plane */
            name: string;
            /** @description 语义化版本号，构建期经 ldflags 注入 */
            version: string;
            /** @description 编译所用 Go 运行时版本（runtime.Version()） */
            goVersion: string;
            /**
             * Format: date-time
             * @description 服务端当前时间（UTC，RFC3339）
             */
            now: string;
            /** @description 关键依赖（PostgreSQL）可达则为 true；false 时仪表盘服务健康亮黄 */
            ready: boolean;
        };
        /** @description 组织分组节点（多级自定义树，主数据，§13.4）。 */
        OrgNode: {
            /**
             * Format: uuid
             * @description 节点 ID
             */
            id: string;
            /** @description 父节点 ID；根为 null */
            parentId: string | null;
            /** @description 名称（同父下唯一），如 A公司/B部门 */
            name: string;
            /** @description 物化路径 "/<id>/<id>"，用于子树整体检索与组织→CIDR 展开 */
            path: string;
        };
        OrgTreeNode: {
            /** Format: uuid */
            id: string;
            parentId: string | null;
            name: string;
            path: string;
            children: components["schemas"]["OrgTreeNode"][];
        };
        OrgCreate: {
            /** @description 父节点 ID；缺省创建根节点 */
            parentId?: string | null;
            /** @description 同父下唯一名称 */
            name: string;
        };
        /** @description 改名与/或移动；移动目标不得为自身或其子孙（409 ORG_CYCLE）。 */
        OrgUpdate: {
            name?: string;
            parentId?: string | null;
        };
        /** @description 子网（IPv4/IPv6，挂组织树；FR-C、§13.4）。 */
        Subnet: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description 所属组织节点（组织→子网→租约/台账关联链起点）
             */
            orgId: string;
            name: string;
            /** @enum {integer} */
            family: 4 | 6;
            /** @description 如 10.61.172.0/24 或 2406:172::/64 */
            cidr: string;
            pools: components["schemas"]["AddressPool"][];
            /** @description 下发 Kea 后的 subnet-id（引擎回写） */
            keaSubnetId?: number | null;
            description?: string;
        };
        AddressPool: {
            startAddr: string;
            endAddr: string;
            /**
             * @description excluded=保留段（§13.4 冻结不下发）
             * @default dynamic
             * @enum {string}
             */
            kind: "dynamic" | "pd" | "excluded";
        };
        SubnetCreate: {
            /** Format: uuid */
            orgId: string;
            name: string;
            /** @enum {integer} */
            family: 4 | 6;
            cidr: string;
            pools?: components["schemas"]["AddressPool"][];
            /**
             * @description true 时仅生成并校验 Kea 配置，不实际下发（§12.2 约定 5）
             * @default false
             */
            dryRun: boolean;
            description?: string;
        };
        SubnetUpdate: {
            name?: string;
            pools?: components["schemas"]["AddressPool"][];
            description?: string;
        };
        /** @description 列表（可按组织/族过滤） */
        SubnetList: {
            items: components["schemas"]["Subnet"][];
            total?: number;
        };
        /**
         * @description 地址六态（§13.4 颜色规范）：在线=租约活跃近似（绿）/空闲（灰蓝）/保留冻结（黄）/静态绑定（蓝）/过期宽限（橙）/冲突（红）
         * @enum {string}
         */
        LedgerState: "online" | "available" | "reserved" | "static" | "grace" | "conflict";
        LedgerRow: {
            /** @description IPv4 逐地址；IPv6 为子网级汇总行（/64 前缀） */
            address: string;
            /** @enum {integer} */
            family: 4 | 6;
            state: components["schemas"]["LedgerState"];
            /** @description 绑定/租约关联 MAC（六态中 online/static/grace/conflict 通常有） */
            mac?: string;
            hostname?: string;
            /** @description 资产登记使用人（asset 表，以 MAC 为键） */
            owner?: string;
            /**
             * Format: date-time
             * @description 租约到期时间（在线态展示）
             */
            leaseExpiry?: string;
            /** Format: uuid */
            subnetId?: string;
            /** @description 游标键："{family}:{address}"，排序稳定 */
            poolIndex?: string;
        };
        LedgerPage: {
            items: components["schemas"]["LedgerRow"][];
            /** @description 下一页游标；空=已到尾页 */
            nextCursor?: string;
            /** @description 满足过滤的总行数（v4 逐地址计数） */
            total?: number;
        };
        ReserveRequest: {
            /** Format: uuid */
            subnetId: string;
            address: string;
            /** @description 保留原因（审计） */
            reason?: string;
        };
        BindRequest: {
            /** Format: uuid */
            subnetId: string;
            address: string;
            /** @description 归一化小写冒号格式 */
            mac: string;
            hostname?: string;
        };
        /** @description 资产登记（MAC 为身份键，换址备注不丢；§13.4 资产登记）。 */
        Asset: {
            /** @description 归一化小写冒号格式（aa:bb:cc:dd:ee:ff） */
            mac: string;
            /**
             * Format: uuid
             * @description 所属组织节点（资产→组织→日志关联链）
             */
            orgId?: string;
            /** @description 使用人员 */
            owner: string;
            dept?: string;
            note?: string;
            tags?: string[];
        };
        /** @description 创建/更新（以 MAC 幂等 upsert） */
        AssetUpsert: {
            mac: string;
            /** Format: uuid */
            orgId?: string;
            owner: string;
            dept?: string;
            note?: string;
            tags?: string[];
        };
        AssetList: {
            items: components["schemas"]["Asset"][];
            total?: number;
        };
        /** @description 批量导入单行（CSV 语义；kind ∈ reserve|bind）。 */
        ReservationBulkEntry: {
            /**
             * @description reserve=冻结保留（无 MAC）；bind=静态绑定（需 MAC）
             * @enum {string}
             */
            kind: "reserve" | "bind";
            address: string;
            /** @description kind=bind 必填（归一化小写冒号格式） */
            mac?: string;
            reason?: string;
        };
        ReservationBulkRequest: {
            /** Format: uuid */
            subnetId: string;
            entries: components["schemas"]["ReservationBulkEntry"][];
        };
        /** @description 批量结果（全部或全不：任一失败整体回滚）。 */
        ReservationBulkResult: {
            /** @description 是否全部成功（false=整体回滚，无任何写入） */
            ok: boolean;
            /** @description 成功应用条数（ok=true 时=entries 数） */
            applied: number;
            failures: {
                /** @description 原始行号（1 起） */
                line: number;
                /** @description 失败原因（占用/非法 MAC/地址越池等） */
                reason: string;
            }[];
        };
        /** @description DNS 上游服务器（FR-B-01；探活状态灯数据源 F-R4）。 */
        Upstream: {
            /** Format: uuid */
            id: string;
            name: string;
            addrs: string[];
            /** @enum {string} */
            protocol: "udp" | "tcp" | "dot";
            weight: number;
            enabled: boolean;
            /** @description 探活状态（prober 维护） */
            health: {
                up?: boolean;
                rttMs?: number;
                consecutiveFails?: number;
                /** Format: date-time */
                lastCheck?: string;
            };
        };
        UpstreamCreate: {
            name: string;
            addrs: string[];
            /**
             * @default udp
             * @enum {string}
             */
            protocol: "udp" | "tcp" | "dot";
            /** @default 1 */
            weight: number;
            /** @default true */
            enabled: boolean;
        };
        UpstreamUpdate: {
            name?: string;
            addrs?: string[];
            /** @enum {string} */
            protocol?: "udp" | "tcp" | "dot";
            weight?: number;
            enabled?: boolean;
        };
        UpstreamList: {
            items: components["schemas"]["Upstream"][];
            total?: number;
        };
        /** @description 条件转发规则（域名后缀→指定上游；最长后缀优先，FR-B-02）。 */
        ForwardRule: {
            /** Format: uuid */
            id: string;
            /** @description 域名后缀（如 corp.local. 或 . 表示默认）；最长匹配优先 */
            domain: string;
            /** @description 该规则使用的上游（引用 /upstreams） */
            upstreamIds: string[];
            enabled: boolean;
            note?: string;
        };
        ForwardRuleCreate: {
            domain: string;
            upstreamIds: string[];
            /** @default true */
            enabled: boolean;
            note?: string;
            /**
             * @description true 时仅生成 forward_add 命令串并返回，不实际下发
             * @default false
             */
            dryRun: boolean;
        };
        /** @description dryRun 输出（生成的下发命令预览） */
        ForwardRuleDryRun: {
            /** @description 如 ["unbound-control forward_add corp.local. 10.0.0.53@53"] */
            commands: string[];
        };
        ForwardRuleList: {
            items: components["schemas"]["ForwardRule"][];
            total?: number;
        };
        /** @description 本地区域（auth-zone/local-zone，§13.4 解析记录）。 */
        DnsZone: {
            /** Format: uuid */
            id: string;
            /** @description FQDN 如 corp.local. */
            name: string;
            /** @enum {string} */
            kind: "auth" | "local";
            enabled: boolean;
        };
        DnsZoneCreate: {
            name: string;
            /**
             * @default auth
             * @enum {string}
             */
            kind: "auth" | "local";
        };
        /** @description 解析记录。 */
        DnsRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            zoneId: string;
            /** @description 相对名（www）或 FQDN */
            name: string;
            /** @enum {string} */
            recType: "A" | "AAAA" | "CNAME" | "PTR";
            ttl: number;
            /** @description 记录数据（A=IP/CNAME=目标/PTR=域名） */
            rdata: string;
            /** @default true */
            enabled: boolean;
        };
        DnsRecordCreate: {
            name: string;
            /** @enum {string} */
            recType: "A" | "AAAA" | "CNAME" | "PTR";
            /** @default 300 */
            ttl: number;
            rdata: string;
            /** @default true */
            enabled: boolean;
        };
        /** @description 联动记录（只读，来自 DHCP 双栈联动自动生成，§4.4）。 */
        LinkedRecord: {
            name: string;
            /** @enum {string} */
            recType: "A" | "AAAA" | "PTR";
            rdata: string;
            /** @description 来源终端 MAC（联调查证） */
            mac?: string;
        };
        DnsZoneList: {
            items: components["schemas"]["DnsZone"][];
            total?: number;
        };
        DnsRecordList: {
            items: components["schemas"]["DnsRecord"][];
            total?: number;
        };
        /** @description 封禁名单库（内置/自定义/订阅源，FR-B-11~14、D13）。 */
        Blocklist: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            kind: "builtin" | "custom" | "feed";
            /** @description kind=feed 的订阅地址(HTTP) */
            syncUrl?: string | null;
            /** Format: date-time */
            lastSync?: string | null;
            /** @description 版本号（每次同步+1，回滚用） */
            version: number;
        };
        BlocklistCreate: {
            name: string;
            /**
             * @default custom
             * @enum {string}
             */
            kind: "builtin" | "custom" | "feed";
            syncUrl?: string | null;
        };
        /** @description 名单条目（RPZ 语义）。 */
        BlocklistEntry: {
            /** Format: uuid */
            listId: string;
            /** @enum {string} */
            triggerType: "qname" | "response_ip";
            /** @description 域名（*.bad.com 通配）或 CIDR */
            pattern: string;
            /**
             * @default nxdomain
             * @enum {string}
             */
            action: "nxdomain" | "drop" | "tcp_only" | "redirect";
            /** @description action=redirect 的提示页记录名 */
            redirectTarget?: string | null;
            /** @description 拦截报表分类标签 */
            category?: string;
        };
        BlocklistEntryCreate: {
            /** @enum {string} */
            triggerType: "qname" | "response_ip";
            pattern: string;
            /** @enum {string} */
            action: "nxdomain" | "drop" | "tcp_only" | "redirect";
            redirectTarget?: string | null;
            category?: string;
        };
        /** @description 订阅源同步结果。 */
        BlocklistSyncResult: {
            /** Format: uuid */
            listId: string;
            version: number;
            /** @description 本次新增去重后条数 */
            added: number;
            /** @description 同步后库内条数 */
            total: number;
        };
        BlocklistList: {
            items: components["schemas"]["Blocklist"][];
            total?: number;
        };
        BlocklistEntryList: {
            items: components["schemas"]["BlocklistEntry"][];
            total?: number;
        };
        /** @description 封禁策略分组（view×网段×名单×时段，FR-B-15/16、§5.1）。 */
        PolicyGroup: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description 对应 unbound view 名（唯一） */
            viewName: string;
            /** @description 匹配来源网段 */
            cidrs: string[];
            /** @description 生效名单集合(白单优先) */
            listIds: string[];
            /** @description 时段表（cron 展开） */
            schedule?: Record<string, never> | null;
        };
        PolicyGroupCreate: {
            name: string;
            viewName: string;
            cidrs: string[];
            listIds: string[];
            schedule?: Record<string, never> | null;
        };
        /** @description RPZ 增量编译结果。 */
        RpzCompileResult: {
            /** @description rpz zone 名（view_name.rpz） */
            zone: string;
            /** @description 去重后条目数 */
            entries: number;
            /** @description zonefile 路径 */
            path: string;
            /** @description 如 unbound-control auth_zone_reload students.rpz */
            reloadCommand: string;
        };
        /** @description DNS 行为参数（缓存+安全，§13.4 缓存与性能/安全与诊断）。 */
        DnsSettings: {
            /** @description 缓存最小 TTL（秒），0=不限制 */
            cacheMinTtl: number;
            /** @description 缓存最大 TTL（秒） */
            cacheMaxTtl: number;
            /** @description 乐观缓存（RFC 8767，F-R2） */
            serveExpired: boolean;
            /** @description 应答速率限制（FR-B-08） */
            rrlEnabled: boolean;
            /** @description RRL 每秒每客户端配额 */
            rrlRate: number;
            /** @description DNSSEC 校验（FR-B-10） */
            dnssecValidate: boolean;
            /**
             * @description 仅 TCP 响应（防 UDP 放大）
             * @default false
             */
            tcpOnly: boolean;
        };
        /** @description 每域名 TTL 覆盖（F-R3，DDNS/CDN 敏感域名）。 */
        PerDomainTtl: {
            /** @description 域名（可含 *. 前缀） */
            domain: string;
            ttl: number;
        };
        /** @description 清空缓存结果。 */
        FlushResult: {
            /** @description all | <zone> */
            flushed: string;
            /** @description 如 unbound-control flush_zone corp.local. */
            command: string;
        };
        LogRow: {
            /**
             * Format: date-time
             * @description 事件时间（UTC，毫秒精度）
             */
            ts: string;
            /**
             * @description 事件来源：DHCP 租约事件 / DNS 查询
             * @enum {string}
             */
            type: "dhcp" | "dns";
            /** @description 原始日志级别（DEBUG/INFO/ERROR…） */
            severity?: string;
            /** @description 客户端 MAC（12 位小写 hex，归一化关联键；DNS 事件可为空） */
            clientMac?: string;
            /** @description DHCP 租约 IP（v4/v6 文本；按需与组织 CIDR 关联） */
            clientIp?: string;
            /** @description DNS 查询源 IP（v4/v6 文本） */
            sip?: string;
            /** @description 查询域名（DNS 事件） */
            domain?: string;
            /** @description DNS 应答码（NOERROR/NXDOMAIN…） */
            rcode?: string;
            /** @description 动作（lease_commit / resolve / blocked…；封禁拦截见 §5） */
            action?: string;
            /** @description 命中封禁时的策略分类（FR-B-18） */
            category?: string;
            /** @description 原始详情（结构化事件描述） */
            detail?: string;
        };
        LogPage: {
            items: components["schemas"]["LogRow"][];
            /** @description 下一页游标（(ts, client_mac, domain) 元组编码）；空=已到尾页 */
            nextCursor?: string;
            /** @description 满足过滤的总事件数（count() 同条件精确值） */
            total?: number;
        };
        TopEntry: {
            /** @description TopN 维度键：域名或 client_mac（依 by 参数） */
            key: string;
            /** @description 窗口内事件数 */
            count: number;
        };
        TopList: {
            items: components["schemas"]["TopEntry"][];
            /** @description 满足过滤的总事件数（TopN 全体口径） */
            total?: number;
        };
        QpsPoint: {
            /**
             * Format: date-time
             * @description 分桶起点（UTC）
             */
            ts: string;
            /** @description 该桶内事件数 */
            count: number;
        };
        QpsSeries: {
            points: components["schemas"]["QpsPoint"][];
        };
        AuditEntry: {
            /** @description 自增序号（游标 tiebreaker） */
            id: number;
            /**
             * Format: date-time
             * @description 操作时间（UTC）
             */
            ts: string;
            /**
             * @description 调用者类型（§12.3：审计日志区分人/AI；M5 JWT 接入前记录 system）
             * @enum {string}
             */
            actorType: "human" | "bot" | "system";
            /** @description 调用者标识（用户名/账号；匿名=anonymous） */
            actor?: string;
            /** @description token 身份指纹（subject/哈希，非原始令牌；M5 接入后填充） */
            tokenSub?: string;
            /** @description HTTP 方法（仅变更类请求入库 POST/PATCH/DELETE） */
            method: string;
            /** @description 请求路径（含 /api/v1 前缀） */
            path: string;
            /** @description 归一动作（create/update/delete/apply/reserve/bind/sync…） */
            action: string;
            /** @description 归一资源标识（路径参数替换为 {param}，防 ID 噪声） */
            resource: string;
            /** @description 响应状态码 */
            status: number;
            /** @description 补充说明（RFC9457 code 等） */
            detail?: string;
        };
        AuditPage: {
            items: components["schemas"]["AuditEntry"][];
            /** @description 下一页游标（(ts,id) 元组编码）；空=已到尾页 */
            nextCursor?: string;
            /** @description 满足过滤的总条数 */
            total?: number;
        };
        DashboardOverview: {
            /**
             * Format: date-time
             * @description 快照生成时间（UTC）
             */
            ts: string;
            /**
             * Format: date-time
             * @description 「今日」口径起点（UTC 当日 00:00）
             */
            todayStart?: string;
            /** @description 今日活跃终端数（DHCP 日志 distinct client_ip，租约活跃近似 §13.4） */
            onlineNow: number;
            /** @description 24h 逐小时活跃终端趋势（不足补零） */
            onlineTrend: {
                /** Format: date-time */
                ts: string;
                count: number;
            }[];
            /** @description 今日新增 MAC（近 7 天窗口内首见日=今日）；无数据源时 null */
            newTerminals?: number | null;
            /** @description 离线终端（前 24h 有活动、今日未见） */
            offlineTerminals?: number | null;
            services: {
                postgres: components["schemas"]["HealthLight"];
                clickhouse: components["schemas"]["HealthLight"];
                kea: components["schemas"]["HealthLight"];
                unbound: components["schemas"]["HealthLight"];
            };
            dns?: {
                /** @description 近 5 分钟 DNS QPS（计数/300 秒） */
                qps5m?: number | null;
                /** @description 缓存命中率（unbound 未输出命中语义日志前恒为 null，§6 遗留②） */
                hitRatePct?: number | null;
                /** @description 今日拦截量（action=blocked；vector 归一化增强 M4-001 遗留② 前为 0/null） */
                blockedToday?: number | null;
            };
            /** @description 池利用率 Top5（used=今日池区间内 distinct client_ip；capacity=区间地址数） */
            poolUtilTop?: components["schemas"]["PoolUtilization"][];
            /** @description 双栈联动成功率（active/(active+conflict) ×100；绑定仓储不可用时 null） */
            coherenceSuccessRatePct?: number | null;
        };
        PoolUtilization: {
            /** Format: uuid */
            subnetId: string;
            name: string;
            /** @description 所属子网 CIDR */
            cidr: string;
            /** @description 池序号（0 起） */
            poolIndex: string;
            /** @description 今日区间内 distinct client_ip */
            used: number;
            /** @description 池区间容量（/127+ 大段按 uint64 饱和展示） */
            capacity: number;
            /** @description 利用率百分比（capacity=0 时 0） */
            pct: number;
        };
        AuthLoginResult: {
            /** @description 访问令牌（PoC 为 HMAC-SHA256 签名 userId.exp，非标准 JWT） */
            accessToken: string;
        };
        AuthLoginRequest: {
            /** @description 账号（PoC 仅 admin） */
            username: string;
            /** @description 口令（环境变量 IPAM_POC_PASSWORD，缺省 admin123） */
            password: string;
        };
        UserInfo: {
            userId: string;
            username: string;
            /** @description 昵称 */
            realName: string;
            /** @description 头像 URL（PoC 返回空串） */
            avatar?: string;
            /** @description 角色码（PoC 固定 ['admin']） */
            roles: string[];
            desc?: string;
            /** @description 登录后默认跳转（仪表盘总览 /overview） */
            homePath: string;
            token?: string;
        };
        /** @description 权限码集合（与 OpenAPI scope 同源预留；PoC 空=按钮级权限不启用） */
        AuthCodesList: string[];
        AuthLogoutDone: {
            ok?: boolean;
        };
        /** @description RFC 9457 问题详情。type/code 字段供机器判读，AI agent 可据此自纠重试（§12.2 约定 4）。 */
        Problem: {
            /** @description 问题类型 URI，稳定不变供程序匹配 */
            type: string;
            /** @description 人类可读摘要 */
            title: string;
            /** @description HTTP 状态码 */
            status: number;
            /** @description 具体原因说明（不含敏感信息） */
            detail?: string;
            /** @description 业务错误码（如 PLATFORM_DB_DOWN），枚举随端点文档化 */
            code?: string;
            /** @description 出错请求的路径 */
            instance?: string;
        };
        /**
         * @description 服务健康灯（unknown=未配置探测地址或 PoC 模式）
         * @enum {string}
         */
        HealthLight: "up" | "down" | "unknown";
    };
    responses: {
        /** @description 错误响应（RFC 9457 Problem Details） */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 令牌缺失/无效/过期 */
        AuthUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    type: string;
                    title: string;
                    status: number;
                    detail?: string;
                    code?: string;
                };
            };
        };
        /** @description 过滤参数非法（时间窗超限/格式错误） */
        LogBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    type: string;
                    title: string;
                    status: number;
                    detail?: string;
                    code?: string;
                    instance?: string;
                };
            };
        };
        /** @description ClickHouse 不可达 */
        LogDown: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    type: string;
                    title: string;
                    status: number;
                    detail?: string;
                    code?: string;
                    instance?: string;
                };
            };
        };
        /** @description 子网列表 */
        SubnetListOK: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SubnetList"];
            };
        };
        /** @description 创建成功（含 dryRun 结果） */
        SubnetCreated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Subnet"];
            };
        };
        /** @description 子网仍被引用（如租约/模板）或 Kea 下发失败回滚（409/503） */
        SubnetInUseError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    type: string;
                    title: string;
                    status: number;
                    detail?: string;
                    code?: string;
                    instance?: string;
                };
            };
        };
        /** @description 更新成功 */
        SubnetUpdated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Subnet"];
            };
        };
        /** @description 组织树（嵌套结构，listOrgTree） */
        OrgTree: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OrgTreeNode"][];
            };
        };
        /** @description 创建成功 */
        OrgCreated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OrgNode"];
            };
        };
        /** @description 资源不存在（404） */
        NotFound404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": unknown;
            };
        };
        /** @description 节点仍被引用或含子节点，禁止删除（409） */
        OrgInUseError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": unknown;
            };
        };
        /** @description 更新成功 */
        OrgUpdated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OrgNode"];
            };
        };
    };
    parameters: {
        /** @description 组织节点 ID */
        OrgId: string;
        SubnetId: string;
        /** @description 时间窗起点（UTC，必填）；窗口上限 31 天 */
        LogFrom: string;
        /** @description 时间窗终点（UTC，缺省=当前时间） */
        LogTo: string;
        /** @description 事件来源过滤 */
        LogType: "dhcp" | "dns";
        /** @description 客户端 MAC 过滤（冒号分隔或 12 位 hex，服务端归一化后匹配） */
        LogMac: string;
        /** @description 客户端 IP 过滤：精确地址或 CIDR（对 client_ip/sip 任一命中） */
        LogIp: string;
        /** @description 域名子串过滤（不区分大小写；DNS 事件） */
        LogDomain: string;
        /** @description 动作过滤（lease_commit / resolve / blocked…） */
        LogAction: string;
        /** @description 组织过滤：展开该节点子树全部 CIDR ∪ 组内资产 MAC 后查询（§13.4 关联链） */
        LogOrgId: string;
        /** @description 分页游标（取自上一页 nextCursor） */
        LogCursor: string;
        /** @description 每页条数 */
        LogPageSize: number;
        /** @description TopN 维度：domain=域名 / client=客户端 MAC */
        LogBy: "domain" | "client";
        /** @description TopN 返回条数 */
        LogLimit: number;
        /** @description QPS 分桶秒数 */
        LogIntervalSec: number;
        /** @description 导出行数上限（CSV 单次转储，超限截断） */
        LogExportLimit: number;
        /** @description 区域 ID */
        ZoneId: string;
        /** @description 子网 ID */
        SubnetIdParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description 令牌 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLoginResult"];
                };
            };
            /** @description 账号或口令错误 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getAuthUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户信息（vben UserInfo 形状） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            401: components["responses"]["AuthUnauthorized"];
        };
    };
    getAuthUserInfoAlias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            401: components["responses"]["AuthUnauthorized"];
        };
    };
    listAuthCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 权限码列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthCodesList"];
                };
            };
            401: components["responses"]["AuthUnauthorized"];
        };
    };
    logoutAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已注销 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLogoutDone"];
                };
            };
        };
    };
    getDashboardOverview: {
        parameters: {
            query?: {
                /** @description 池利用率 TopN 条数 */
                poolTopN?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 聚合快照 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverview"];
                };
            };
            500: components["responses"]["Problem"];
        };
    };
    listLogs: {
        parameters: {
            query: {
                /** @description 时间窗起点（UTC，必填）；窗口上限 31 天 */
                from: components["parameters"]["LogFrom"];
                /** @description 时间窗终点（UTC，缺省=当前时间） */
                to?: components["parameters"]["LogTo"];
                /** @description 事件来源过滤 */
                type?: components["parameters"]["LogType"];
                /** @description 客户端 MAC 过滤（冒号分隔或 12 位 hex，服务端归一化后匹配） */
                mac?: components["parameters"]["LogMac"];
                /** @description 客户端 IP 过滤：精确地址或 CIDR（对 client_ip/sip 任一命中） */
                ip?: components["parameters"]["LogIp"];
                /** @description 域名子串过滤（不区分大小写；DNS 事件） */
                domain?: components["parameters"]["LogDomain"];
                /** @description 动作过滤（lease_commit / resolve / blocked…） */
                action?: components["parameters"]["LogAction"];
                /** @description 组织过滤：展开该节点子树全部 CIDR ∪ 组内资产 MAC 后查询（§13.4 关联链） */
                orgId?: components["parameters"]["LogOrgId"];
                /** @description 分页游标（取自上一页 nextCursor） */
                cursor?: components["parameters"]["LogCursor"];
                /** @description 每页条数 */
                pageSize?: components["parameters"]["LogPageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 日志页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogPage"];
                };
            };
            400: components["responses"]["LogBadRequest"];
            503: components["responses"]["LogDown"];
        };
    };
    streamLogTail: {
        parameters: {
            query?: {
                /** @description 起始位点（UTC，缺省=当前时间；也可用 Last-Event-ID 续传） */
                from?: string;
                /** @description 事件来源过滤 */
                type?: components["parameters"]["LogType"];
                /** @description 客户端 MAC 过滤（冒号分隔或 12 位 hex，服务端归一化后匹配） */
                mac?: components["parameters"]["LogMac"];
                /** @description 客户端 IP 过滤：精确地址或 CIDR（对 client_ip/sip 任一命中） */
                ip?: components["parameters"]["LogIp"];
                /** @description 域名子串过滤（不区分大小写；DNS 事件） */
                domain?: components["parameters"]["LogDomain"];
                /** @description 动作过滤（lease_commit / resolve / blocked…） */
                action?: components["parameters"]["LogAction"];
                /** @description 组织过滤：展开该节点子树全部 CIDR ∪ 组内资产 MAC 后查询（§13.4 关联链） */
                orgId?: components["parameters"]["LogOrgId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 事件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["LogBadRequest"];
        };
    };
    listLogTop: {
        parameters: {
            query: {
                /** @description 时间窗起点（UTC，必填）；窗口上限 31 天 */
                from: components["parameters"]["LogFrom"];
                /** @description 时间窗终点（UTC，缺省=当前时间） */
                to?: components["parameters"]["LogTo"];
                /** @description 事件来源过滤 */
                type?: components["parameters"]["LogType"];
                /** @description 客户端 IP 过滤：精确地址或 CIDR（对 client_ip/sip 任一命中） */
                ip?: components["parameters"]["LogIp"];
                /** @description 动作过滤（lease_commit / resolve / blocked…） */
                action?: components["parameters"]["LogAction"];
                /** @description 组织过滤：展开该节点子树全部 CIDR ∪ 组内资产 MAC 后查询（§13.4 关联链） */
                orgId?: components["parameters"]["LogOrgId"];
                /** @description TopN 维度：domain=域名 / client=客户端 MAC */
                by?: components["parameters"]["LogBy"];
                /** @description TopN 返回条数 */
                limit?: components["parameters"]["LogLimit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TopN 列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopList"];
                };
            };
            400: components["responses"]["LogBadRequest"];
            503: components["responses"]["LogDown"];
        };
    };
    getLogQps: {
        parameters: {
            query: {
                /** @description 时间窗起点（UTC，必填）；窗口上限 31 天 */
                from: components["parameters"]["LogFrom"];
                /** @description 时间窗终点（UTC，缺省=当前时间） */
                to?: components["parameters"]["LogTo"];
                /** @description 事件来源过滤 */
                type?: components["parameters"]["LogType"];
                /** @description 动作过滤（lease_commit / resolve / blocked…） */
                action?: components["parameters"]["LogAction"];
                /** @description 组织过滤：展开该节点子树全部 CIDR ∪ 组内资产 MAC 后查询（§13.4 关联链） */
                orgId?: components["parameters"]["LogOrgId"];
                /** @description QPS 分桶秒数 */
                intervalSec?: components["parameters"]["LogIntervalSec"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description QPS 时序 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QpsSeries"];
                };
            };
            400: components["responses"]["LogBadRequest"];
            503: components["responses"]["LogDown"];
        };
    };
    listOperationAudits: {
        parameters: {
            query: {
                /** @description 时间窗起点（UTC）；窗口上限 31 天 */
                from: string;
                /** @description 时间窗终点（UTC，缺省=当前时间） */
                to?: string;
                /** @description 调用者类型过滤（§12.3） */
                actorType?: "human" | "bot" | "system";
                /** @description 动作过滤（create/update/delete…） */
                action?: string;
                /** @description 资源/路径子串过滤（不区分大小写） */
                q?: string;
                /** @description 分页游标（取自上一页 nextCursor） */
                cursor?: string;
                /** @description 每页条数 */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审计页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description 过滤参数非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        detail?: string;
                        code?: string;
                    };
                };
            };
        };
    };
    exportLogs: {
        parameters: {
            query: {
                /** @description 时间窗起点（UTC，必填）；窗口上限 31 天 */
                from: components["parameters"]["LogFrom"];
                /** @description 时间窗终点（UTC，缺省=当前时间） */
                to?: components["parameters"]["LogTo"];
                /** @description 事件来源过滤 */
                type?: components["parameters"]["LogType"];
                /** @description 客户端 MAC 过滤（冒号分隔或 12 位 hex，服务端归一化后匹配） */
                mac?: components["parameters"]["LogMac"];
                /** @description 客户端 IP 过滤：精确地址或 CIDR（对 client_ip/sip 任一命中） */
                ip?: components["parameters"]["LogIp"];
                /** @description 域名子串过滤（不区分大小写；DNS 事件） */
                domain?: components["parameters"]["LogDomain"];
                /** @description 动作过滤（lease_commit / resolve / blocked…） */
                action?: components["parameters"]["LogAction"];
                /** @description 组织过滤：展开该节点子树全部 CIDR ∪ 组内资产 MAC 后查询（§13.4 关联链） */
                orgId?: components["parameters"]["LogOrgId"];
                /** @description 导出行数上限（CSV 单次转储，超限截断） */
                exportLimit?: components["parameters"]["LogExportLimit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV 文本 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            400: components["responses"]["LogBadRequest"];
            503: components["responses"]["LogDown"];
        };
    };
    applyDnsConf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 应用成功（回显合成摘要） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        applied?: Record<string, never>;
                    };
                    examples: unknown;
                };
            };
            /** @description checkconf 校验失败（未生效） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                };
            };
        };
    };
    getDnsSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前参数 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsSettings"];
                };
            };
        };
    };
    updateDnsSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DnsSettings"];
            };
        };
        responses: {
            /** @description 已更新并 reload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsSettings"];
                };
            };
            /** @description checkconf 校验失败（未生效） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                };
            };
        };
    };
    listTtlOverrides: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 覆盖列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PerDomainTtl"][];
                    };
                };
            };
        };
    };
    upsertTtlOverride: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PerDomainTtl"];
            };
        };
        responses: {
            /** @description 已设置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerDomainTtl"];
                };
            };
        };
    };
    flushCache: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description 指定 zone 名，缺省清空全部 */
                    zone?: string | null;
                };
            };
        };
        responses: {
            /** @description 已清空 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlushResult"];
                };
            };
        };
    };
    listBlocklists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlocklistList"];
                    examples: unknown;
                };
            };
        };
    };
    createBlocklist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlocklistCreate"];
            };
        };
        responses: {
            /** @description OK */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blocklist"];
                    examples: unknown;
                };
            };
        };
    };
    syncBlocklist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlocklistSyncResult"];
                    examples: unknown;
                };
            };
            /** @description 订阅源不可达/解析失败（旧版保留） */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                };
            };
        };
    };
    listBlocklistEntries: {
        parameters: {
            query?: {
                /** @description 关键字（pattern 模糊） */
                q?: string;
            };
            header?: never;
            path: {
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlocklistEntryList"];
                    examples: unknown;
                };
            };
        };
    };
    addBlocklistEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlocklistEntryCreate"];
            };
        };
        responses: {
            /** @description OK */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlocklistEntry"];
                    examples: unknown;
                };
            };
        };
    };
    listPolicyGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyGroup"];
                    examples: unknown;
                };
            };
        };
    };
    createPolicyGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyGroupCreate"];
            };
        };
        responses: {
            /** @description OK */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyGroup"];
                    examples: unknown;
                };
            };
        };
    };
    compilePolicyGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RpzCompileResult"];
                    examples: unknown;
                };
            };
        };
    };
    listDnsZones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 区域列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsZoneList"];
                };
            };
        };
    };
    createDnsZone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DnsZoneCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsZone"];
                };
            };
        };
    };
    listDnsRecords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 区域 ID */
                zoneId: components["parameters"]["ZoneId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 记录列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsRecordList"];
                };
            };
        };
    };
    createDnsRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 区域 ID */
                zoneId: components["parameters"]["ZoneId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DnsRecordCreate"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsRecord"];
                };
            };
        };
    };
    listLinkedRecords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 区域 ID */
                zoneId: components["parameters"]["ZoneId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 联动记录列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["LinkedRecord"][];
                    };
                };
            };
        };
    };
    exportDnsZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 区域 ID */
                zoneId: components["parameters"]["ZoneId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description zonefile 文本 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    deleteDnsZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 区域 ID */
                zoneId: components["parameters"]["ZoneId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listForwardRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForwardRuleList"];
                    examples: unknown;
                };
            };
        };
    };
    createForwardRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForwardRuleCreate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForwardRuleDryRun"];
                    examples: unknown;
                };
            };
            /** @description OK */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForwardRule"];
                    examples: unknown;
                };
            };
        };
    };
    deleteForwardRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateForwardRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    upstreamIds?: string[];
                    enabled?: boolean;
                    note?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForwardRule"];
                    examples: unknown;
                };
            };
        };
    };
    listUpstreams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamList"];
                    examples: unknown;
                };
            };
        };
    };
    createUpstream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpstreamCreate"];
            };
        };
        responses: {
            /** @description OK */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upstream"];
                    examples: unknown;
                };
            };
        };
    };
    deleteUpstream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upstreamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateUpstream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upstreamId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpstreamUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upstream"];
                    examples: unknown;
                };
            };
        };
    };
    bulkReservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationBulkRequest"];
            };
        };
        responses: {
            /** @description 批量结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationBulkResult"];
                };
            };
            /** @description Kea 下发失败（已整体回滚） */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                };
            };
        };
    };
    listAssets: {
        parameters: {
            query?: {
                orgId?: string;
                /** @description 关键字：MAC/owner/dept 模糊匹配 */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资产列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetList"];
                };
            };
        };
    };
    upsertAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetUpsert"];
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
        };
    };
    deleteAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mac: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 资产不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listLedger: {
        parameters: {
            query?: {
                orgId?: string;
                family?: 4 | 6;
                state?: components["schemas"]["LedgerState"];
                cursor?: string;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 台账页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerPage"];
                };
            };
        };
    };
    reserveAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveRequest"];
            };
        };
        responses: {
            /** @description 已保留 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 地址已被占用（绑定/在线） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                };
            };
        };
    };
    bindStatic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindRequest"];
            };
        };
        responses: {
            /** @description 已绑定 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 地址已被占用 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                };
            };
        };
    };
    listSubnets: {
        parameters: {
            query?: {
                orgId?: string;
                family?: 4 | 6;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SubnetListOK"];
        };
    };
    createSubnet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubnetCreate"];
            };
        };
        responses: {
            201: components["responses"]["SubnetCreated"];
            503: components["responses"]["SubnetInUseError"];
        };
    };
    deleteSubnet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 子网 ID */
                subnetId: components["parameters"]["SubnetIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 子网不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                };
            };
            /** @description 仍被引用 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                };
            };
        };
    };
    updateSubnet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 子网 ID */
                subnetId: components["parameters"]["SubnetIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubnetUpdate"];
            };
        };
        responses: {
            200: components["responses"]["SubnetUpdated"];
            /** @description 子网不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        type: string;
                        title: string;
                        status: number;
                        code?: string;
                    };
                };
            };
            503: components["responses"]["SubnetInUseError"];
        };
    };
    listOrgTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OrgTree"];
        };
    };
    createOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgCreate"];
            };
        };
        responses: {
            201: components["responses"]["OrgCreated"];
            /** @description 同父重名 / 父不存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    deleteOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 组织节点 ID */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound404"];
            409: components["responses"]["OrgInUseError"];
        };
    };
    updateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 组织节点 ID */
                orgId: components["parameters"]["OrgId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgUpdate"];
            };
        };
        responses: {
            200: components["responses"]["OrgUpdated"];
            404: components["responses"]["NotFound404"];
            /** @description 目标父为自身子孙（ORG_CYCLE） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    getSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 系统信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
            500: components["responses"]["Problem"];
        };
    };
}
